# This is a basic workflow to help you get started with Actions

name: Dione Maven Build CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ *release* ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Step 1 - Checkout DIONE main branch from GitHub
        uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Step 2 Set up JDK 1.8
        uses: actions/setup-java@v2.1.0
        with:
          java-version: 1.8
          distribution: jdk

      # Runs a set of commands using the runners shell
      - name: Step 3 GitHub Action Pre Deploy Phase
        run: |
            openssl aes-256-cbc -K $encrypted_011506a0d8d1_key -iv $encrypted_011506a0d8d1_iv -in gpg.key.enc -out gpg.key -d
            gpg --import gpg.key
            export GPG_KEY_FILE="$PWD/gpg.key"

      # Runs a set of commands using the runners shell
      - name: Step 4 GitHub Action Builds and Deploy Dione project
        run:
          mvn -DskipTests --settings settings-ossrh.xml -Prelease -B -V deploy --file pom.xml

        # Runs a set of commands using the runners shell
        - name: Step 5 GitHub Action list files in current directory
          run:
            ls -a

        # Runs a set of commands using the runners shell
        - name: Step 6 GitHub Action list files in current  target directory
          run: |
            cd target
            ls -a
